### ISSUE TITLE
New columns

### ISSUE THREAD

**Issue by Zsupi** [Dinnyeee/Haziorvos#17]
#### Todo:
- [ ] Add priority column for Case
  -  High, Medium, Low
- [ ] Add status column for Case
  - New, InProgress, Done
- [ ] Add Title for Case
- [ ] Add Birthday for Child
